version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: filmdb
      POSTGRES_USER: filmuser
      POSTGRES_PASSWORD: secret
    networks:
      - filmnet

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && gunicorn main_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://filmuser:secret@db:5432/filmdb
    depends_on:
      - db
    networks:
      - filmnet

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - filmnet

volumes:
  postgres_data:

networks:
  filmnet:
