# Generated by Django 4.2.23 on 2025-06-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor", old_name="name", new_name="first_name",
        ),
        migrations.RenameField(
            model_name="review", old_name="comment", new_name="description",
        ),
        migrations.RemoveField(model_name="review", name="created_at",),
        migrations.AddField(
            model_name="actor",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
